export type CurriculumDay = {
  day: number
  type: 'video' | 'article'
  refId: string
  part?: { current: number; total: number; startMin: number; endMin: number }
}

export const CURRICULUM: CurriculumDay[] = [
  { day: 1,  type: 'article', refId: 'healthcentral-prt' },
  { day: 2,  type: 'video',   refId: 'pv8PtT_4rjk', part: { current: 1, total: 2, startMin: 0,   endMin: 25  } },
  { day: 3,  type: 'video',   refId: 'pv8PtT_4rjk', part: { current: 2, total: 2, startMin: 25,  endMin: 49  } },
  { day: 4,  type: 'video',   refId: '0VyH1laOd2M', part: { current: 1, total: 2, startMin: 0,   endMin: 27  } },
  { day: 5,  type: 'video',   refId: '0VyH1laOd2M', part: { current: 2, total: 2, startMin: 27,  endMin: 53  } },
  { day: 6,  type: 'article', refId: 'pt-chronic-pain-head' },
  { day: 7,  type: 'video',   refId: 'cbF2HMXtfZ4', part: { current: 1, total: 4, startMin: 0,   endMin: 35  } },
  { day: 8,  type: 'video',   refId: 'cbF2HMXtfZ4', part: { current: 2, total: 4, startMin: 35,  endMin: 69  } },
  { day: 9,  type: 'video',   refId: 'cbF2HMXtfZ4', part: { current: 3, total: 4, startMin: 69,  endMin: 103 } },
  { day: 10, type: 'video',   refId: 'cbF2HMXtfZ4', part: { current: 4, total: 4, startMin: 103, endMin: 138 } },
  { day: 11, type: 'article', refId: 'schubiner-pain-message' },
  { day: 12, type: 'video',   refId: 'gwd-wLdIHjs' },
  { day: 13, type: 'article', refId: 'painscience-mri' },
  { day: 14, type: 'video',   refId: 'Lw1D_UvzIDA' },
  { day: 15, type: 'video',   refId: 'fMwQsuPXODk' },
  { day: 16, type: 'article', refId: 'jensen1994' },
  { day: 17, type: 'video',   refId: 'tJmtnvCz_KU' },
  { day: 18, type: 'article', refId: 'schierling' },
  { day: 19, type: 'video',   refId: 'KGbE_uUVuRs' },
  { day: 20, type: 'article', refId: 'andrews2002' },
  { day: 21, type: 'article', refId: 'elbarzouhi2013' },
  { day: 22, type: 'article', refId: 'smithsonian-nocebo' },
  { day: 23, type: 'video',   refId: 'kYK7utae7Cg', part: { current: 1, total: 4, startMin: 0,   endMin: 29  } },
  { day: 24, type: 'video',   refId: 'kYK7utae7Cg', part: { current: 2, total: 4, startMin: 29,  endMin: 58  } },
  { day: 25, type: 'video',   refId: 'kYK7utae7Cg', part: { current: 3, total: 4, startMin: 58,  endMin: 87  } },
  { day: 26, type: 'video',   refId: 'kYK7utae7Cg', part: { current: 4, total: 4, startMin: 87,  endMin: 116 } },
  { day: 27, type: 'article', refId: 'petersen2014' },
  { day: 28, type: 'video',   refId: 'I8GG7sFQ3xw' },
  { day: 29, type: 'video',   refId: 'MDDp6sqVG_k' },
  { day: 30, type: 'article', refId: 'hashmi2013' },
  { day: 31, type: 'video',   refId: 'ZOHPmp1Rd38', part: { current: 1, total: 2, startMin: 0,   endMin: 40  } },
  { day: 32, type: 'video',   refId: 'ZOHPmp1Rd38', part: { current: 2, total: 2, startMin: 40,  endMin: 79  } },
  { day: 33, type: 'article', refId: 'chou' },
  { day: 34, type: 'video',   refId: 'sRutceG1gks', part: { current: 1, total: 2, startMin: 0,   endMin: 26  } },
  { day: 35, type: 'video',   refId: 'sRutceG1gks', part: { current: 2, total: 2, startMin: 26,  endMin: 52  } },
  { day: 36, type: 'article', refId: 'ashar2022' },
  { day: 37, type: 'article', refId: 'psrt2021' },
  { day: 38, type: 'article', refId: 'nih-scale' },
  { day: 39, type: 'article', refId: 'deyo-overtreatment' },
  { day: 40, type: 'video',   refId: 'pHM45IXkXeM' },
  { day: 41, type: 'video',   refId: 'ic6se1fOpkc' },
  { day: 42, type: 'video',   refId: 'kB4gvqDsVnA', part: { current: 1, total: 2, startMin: 0,  endMin: 18 } },
  { day: 43, type: 'video',   refId: 'kB4gvqDsVnA', part: { current: 2, total: 2, startMin: 18, endMin: 35 } },
  { day: 44, type: 'video',   refId: 'dWD3SwfzA0c', part: { current: 1, total: 4, startMin: 0,  endMin: 18 } },
  { day: 45, type: 'video',   refId: 'dWD3SwfzA0c', part: { current: 2, total: 4, startMin: 18, endMin: 36 } },
  { day: 46, type: 'video',   refId: 'dWD3SwfzA0c', part: { current: 3, total: 4, startMin: 36, endMin: 54 } },
  { day: 47, type: 'video',   refId: 'dWD3SwfzA0c', part: { current: 4, total: 4, startMin: 54, endMin: 73 } },
  { day: 48, type: 'video',   refId: 'jVGbwAPEJxM', part: { current: 1, total: 4, startMin: 0,  endMin: 19 } },
  { day: 49, type: 'video',   refId: 'jVGbwAPEJxM', part: { current: 2, total: 4, startMin: 19, endMin: 38 } },
  { day: 50, type: 'video',   refId: 'jVGbwAPEJxM', part: { current: 3, total: 4, startMin: 38, endMin: 57 } },
  { day: 51, type: 'video',   refId: 'jVGbwAPEJxM', part: { current: 4, total: 4, startMin: 57, endMin: 77 } },
]
